# Generated by Django 3.0.1 on 2020-02-06 05:17

from django.db import migrations, models
import uuid
import votacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_chapa', models.CharField(max_length=50)),
                ('nome_candidato', models.CharField(max_length=50)),
                ('nome_vice', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=2)),
                ('profile', models.ImageField(upload_to=votacao.models.get_path_photo_profile)),
                ('numero_votos', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
