# Generated by Django 2.2.6 on 2019-10-20 21:34

from django.db import migrations, models
import uuid
import votacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_chapa', models.CharField(max_length=50)),
                ('nome_candidato', models.CharField(max_length=50)),
                ('nome_vice', models.CharField(max_length=50)),
                ('numero_chapa', models.IntegerField(max_length=4)),
                ('votos', models.IntegerField(verbose_name=models.IntegerField(default=0))),
                ('profile', models.ImageField(upload_to=votacao.models.get_path_photo_profile)),
            ],
        ),
    ]
