# Generated by Django 2.2.6 on 2019-11-04 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapa',
            name='numero_chapa',
        ),
        migrations.RemoveField(
            model_name='chapa',
            name='votos',
        ),
        migrations.AddField(
            model_name='chapa',
            name='numero',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
